# A basic CI script to automate publishing @ngx-dummy/select-simple lib
name: npm-deploy
on:
  push:
    branches:
      - main
      - 'v9'

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.repository_owner, 'ngx-dummy')

    name: Deploying package to npm packages registry
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ngx-dummy'
      - run: |
          echo Installing..!
          npm ci

      - run: npm run ci:prepublish:npm --if-present

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          checkVersion: true
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: 'public'
          registry: 'https://registry.npmjs.org/'
          package: './dist/packages/select-simple/package.json'

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
