# A basic CI script to automate publishing @ngx-dummy/select-simple lib
name: npm-deploy
on:
  push:
    branches:
      - main
      - 'v9'

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.repository_owner, 'ngx-dummy')

    name: Deploying package to npm packages registry
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ngx-dummy'
      - run: |
          echo Installing..!
          npm ci

      - run: npm run ci:prepublish:npm --if-present

      - id: publish
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          create_tag: "false"
          commit_pattern: "^Release (\\S+)"
          workspace: "./dist/packages/select-simple"
          publish_args: "--non-interactive"

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
